config/routes.rb
RachelBlog3::Application.routes.draw do
  root :to => 'posts#index'
  get '/posts' => 'posts#index', as: 'posts'
  get '/posts/new' => 'posts#new'
  get '/posts/:id' => 'posts#show', as: 'post'
  post '/posts' => 'posts#create'
  get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'
  put '/posts/:id' => 'posts#update'
  delete '/posts/:id' => 'posts#destroy', as: 'delete_post'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController <ApplicationController

  def index
    @name = "Rachel"
    @posts = Post.all
    respond_to do |format|
      format.html # show default view
      format.json {render json: @products}
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  # this is for the new form:
  def new
    @post = Post.new
  end

  def create 
    @post = Post.new(params[:post])
    if @post.save
      redirect_to post_path(@post.id), notice: "created successfully"
    else
      render action: 'new'
    end
  end

  # def update
  #   @post = Post.find(params[:id])
  # end
  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    # option 1 - updating post:
    # @post.title = params[:post][:title]
    # @post.body = params[:post][:body]
    # @post.save

     # option 2 - updating post:
     # @post.update_attributes(
     #  title: params[:post][:title],
     #  body: params[:post][:body]
     # )
    

     # option 3 - updating post:
     # @post.update_attributes("title"=>"new again!", "body"=>"Boo!")
    

    # if @post.save
    #   redirect_to post_path(@post.id), {notice: 'Post was successfully updated!'}
    # else
    #   render action: 'new'
    # end




    # respond_to do |format|
       # option 4 - updating post:\
      @post.update_attributes(params[:post])
      redirect_to post_path(@post), notice: 'Post was successfully updated!'
  
      

      # if @post.update_attributes(params[:post])
      #   format.html { redirect_to post_path(@post), notice: 'Post was successfully updated!'}
      # else
      #   redirect_to(edit_post)
      # end

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, alert: "Are you sure????" 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RachelBlog3</title>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= params.inspect %>
<%h1= "#{@name}'s Blog" %>

<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>

<% if flash[:alert] %>
	<%= flash[:alert] %>
<% end %>	

<%= yield %>

</body>
</html>

app/views/posts/edit.html.haml
= form_for @post do |f|
	= f.label :title
	= f.text_field :title
	%br
	= f.label :body
	= f.text_area :body, rows: 4
	%br
	= f.submit "UPDATE!"

app/views/posts/index.html.haml
%body
  %h1= "#{@name}'s Blog"
  / -@post.each do |t|
  /   %h2= t.title
  /   %p= t.body

  - @posts.each do |t|
    %h2= link_to t.title, post_path(t)

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br />

  <%= f.label :body %>
  <%= f.text_field :body %><br />

  <%= f.submit %>
<% end %>

app/views/posts/show.html.haml
%body 
	%h2= @post.title
	%p= @post.body
	= link_to 'Edit', edit_post_path(@post)
	%br

	= link_to 'Delete', @post, :method => :delete, :data => { :confirm => 'Are you sure?'} 

/ delete_post_path(@post.id)